<a href="https://colab.research.google.com/github/shaina-12/Artificial-Intelligence/blob/main/Miscellaneous/AND_Gate_Implemetation_Using_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np

In [75]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[0],[0],[1]])
W1 = np.array([[0.3,0.1,0.8],[0.1,0.3,0.2]])
W2 = np.array([[0.7],[0.4],[0.9]])
print(W1)
print(W2)
lr = 0.05

[[0.3 0.1 0.8]
 [0.1 0.3 0.2]]
[[0.7]
 [0.4]
 [0.9]]


In [76]:
def sigmoid(x):
  return 1/(1+np.exp(-x))
def der_sigmoid(x):
  return sigmoid(x)*(1-sigmoid(x))

In [77]:
for epoch in range(5000):
  h = np.dot(X,W1)
  hf = sigmoid(h)
  y = np.dot(hf,W2)
  yf = sigmoid(y)
  E = yf - Y
  L = 1/2*(np.power(E,2))
  dL_dyf = (yf-Y) 
  dyf_dy = yf*(1-yf)
  dy_dw2 = hf
  dL_dw2 = np.dot(dy_dw2.T,dL_dyf*dyf_dy)
  W2 -= lr*dL_dw2
  dL_dyf = (yf-Y) 
  dyf_dy = yf*(1-yf)
  dy_dhf = W2
  dhf_dh = hf*(1-hf)
  dh_dw1 = X
  dL_dhf = np.dot(dL_dyf*dyf_dy,dy_dhf.T)
  dL_dw1 = np.dot(dh_dw1.T,dhf_dh*dL_dhf)
  W1 -= lr*dL_dw1
print(W2)
print(W1)

[[-4.85123792]
 [-5.23514382]
 [ 2.27709934]]
[[ 0.42707884 -2.23358713  1.65243032]
 [-2.71039994  0.02011962  0.38156451]]


In [86]:
point = np.array([0,0])
z = np.dot(point,W1)
h = sigmoid(z)
op = np.dot(h,W2)
y_cap = sigmoid(op)
if (y_cap<0.5):
  print(0)
else:
  print(1)

0


In [11]:
import torch
import torch.nn as nn
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)

In [12]:
input

tensor([[-2.0798, -0.9833,  0.8541],
        [ 0.1033, -0.0686,  2.4684]])

In [13]:
output

tensor([[0.0439, 0.1313, 0.8248],
        [0.0801, 0.0674, 0.8525]])

In [14]:
m

Softmax(dim=1)