<a href="https://colab.research.google.com/github/shaina-12/Artificial-Intelligence/blob/main/Miscellaneous/OR_Gate_Implemetation_Using_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
print(X)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [3]:
Y_target = np.array([[0],[1],[1],[1]])
print(Y_target)

[[0]
 [1]
 [1]
 [1]]


In [4]:
W1 = np.array([[0.3,0.1,0.8],[0.1,0.3,0.2]])
W2 = np.array([[0.7],[0.4],[0.9]])
print(W1)
print(W2)
lr = 0.05

[[0.3 0.1 0.8]
 [0.1 0.3 0.2]]
[[0.7]
 [0.4]
 [0.9]]


In [5]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [6]:
def der_sigmoid(x):
  return sigmoid(x)*(1-sigmoid(x))

In [11]:
for epoch in range(5000):
  Z = np.dot(X,W1)
  H = sigmoid(Z)
  U = np.dot(H,W2)
  Y = sigmoid(U)
  E = Y - Y_target
  L = 1/2*(np.power(E,2))
  dL_dY = Y-Y_target
  dY_dU = Y*(1-Y)
  dU_dW2 = H
  dL_dW2=np.dot(dU_dW2.T,dL_dY*dY_dU)
  W2 -= lr*dL_dW2
  dL_dY = Y-Y_target
  dY_dU = Y*(1-Y)
  dU_dH = W2
  dH_dZ = H*(1-H)
  dZ_dW1 = X
  dL_dH = np.dot(dL_dY*dY_dU,dU_dH.T)
  dL_dW1 = np.dot(dZ_dW1.T,dH_dZ*dL_dH)
  W1 -= lr*dL_dW1
print(W2)
print(W1)

[[ 0.2454737 ]
 [-6.96540005]
 [ 3.06495417]]
[[ 1.29562525 -2.57717316  2.75437081]
 [ 1.22720362 -2.58926193  2.67610644]]


In [16]:
point = np.array([0,0])
z = np.dot(point,W1)
h = sigmoid(z)
op = np.dot(h,W2)
y_cap = sigmoid(op)
print(y_cap)

[0.13853802]
