<a href="https://colab.research.google.com/github/shaina-12/Artificial-Intelligence/blob/main/Miscellaneous/XOR_Gate_Implemetation_Using_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

In [35]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])
W1 = np.array([[0.3,0.1,0.8],[0.1,0.3,0.2]])
W2 = np.array([[0.7],[0.4],[0.9]])
print(W1)
print(W2)
lr = 0.1

[[0.3 0.1 0.8]
 [0.1 0.3 0.2]]
[[0.7]
 [0.4]
 [0.9]]


In [36]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [37]:
for epoch in range(5000):
  h = np.dot(X,W1)
  hf = sigmoid(h)
  y = np.dot(hf,W2)
  yf = sigmoid(y)
  E = yf - Y
  L = 1/2*(np.power(E,2))
  dL_dyf = (yf-Y) 
  dyf_dy = yf*(1-yf)
  dy_dw2 = hf
  dL_dw2 = np.dot(dy_dw2.T,dL_dyf*dyf_dy)
  W2 -= lr*dL_dw2
  dL_dyf = (yf-Y) 
  dyf_dy = yf*(1-yf)
  dy_dhf = W2
  dhf_dh = hf*(1-hf)
  dh_dw1 = X
  dL_dhf = np.dot(dL_dyf*dyf_dy,dy_dhf.T)
  dL_dw1 = np.dot(dh_dw1.T,dhf_dh*dL_dhf)
  W1 -= lr*dL_dw1
print(W2)
print(W1)

[[-2.16646525]
 [-2.45007704]
 [ 3.47588354]]
[[0.892635   0.29553927 3.38185385]
 [0.2553382  0.87200882 3.3657086 ]]


In [47]:
point = np.array([0,0])
z = np.dot(point,W1)
h = sigmoid(z)
op = np.dot(h,W2)
y_cap = sigmoid(op)
if (y_cap<0.5):
  print(0)
else:
  print(1)

0
